# Generated by Django 4.1.3 on 2023-03-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_code', models.CharField(choices=[('1', 'museum-halls'), ('2', 'ferdows-cinema'), ('3', 'tamadon-cinema'), ('4', 'book-shop'), ('5', 'viuna-cafe')], max_length=15, verbose_name='Place Code')),
                ('shot_photo_date', models.DateTimeField(auto_now_add=True)),
                ('image_name', models.ImageField(max_length=50, upload_to='photo/gallery', verbose_name='Picture Name')),
                ('text_info', models.TextField(verbose_name='Information')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('parent_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Parent Code')),
            ],
        ),
    ]
